### ISSUE TITLE
Tapping button with no task selected causes error

### ISSUE THREAD

**Issue by BethJSmith** [NoteTakerPlus/NoteTakerPlus#11]
When one of the buttons at the bottom of the screen (edit note, delete note, complete note) are selected an error occurs. The methods require the selected note but there is no selected note. Needs a quick check to make sure selected note is not null before continuing.

**Comment by harmonise** [comment]
Does this require GUI changes (eg fade out buttons) to indicate when the buttons can't be pressed?

**Comment by BethJSmith** [comment]
Fixed with commit 1087e37.
